### ISSUE TITLE
Can user edit invoice?

### ISSUE THREAD

**Issue by wzulfikar** [j-berman/prinvoice#1]
After I created invoice, there are actions that I can do for given invoice (eg. Send, Download PDF) except to edit the invoice. 

![image](https://user-images.githubusercontent.com/7823011/105991819-d8b5e800-60d6-11eb-915e-d1a421fdae92.png)

I tried to click the list item (assuming that the page will redirect to edit invoice page) but it did nothing. My questions are:

1. Can user edit invoice?
2. If not, is it because the UI implementation is not there yet or it's a limitation from UserBase?

P.S: I absolutely love the software. It's minimalist and straight to the point.

**Comment by j-berman** [comment]
>Can user edit invoice?

Unfortunately not, invoices are immutable

>If not, is it because the UI implementation is not there yet or it's a limitation from UserBase?

UI implementation :) I just didn't get around to it

>P.S: I absolutely love the software. It's minimalist and straight to the point.

Thank you! :D
