### ISSUE TITLE
Can I use my own Userbase instance?

### ISSUE THREAD

**Issue by wzulfikar** [j-berman/prinvoice#3]
In src/config.js, I saw the hardcoded value of userbase app id:

https://github.com/j-berman/prinvoice/blob/c191bcc1fc77fe7379fde7665df2bfdad2874d96/src/config.js#L4

Does it mean that I can use my own Userbase app (eg. create userbase account and use my own userbase app id) as the backend?

Thanks!

**Comment by j-berman** [comment]
Yep, that's exactly what it means :)

Feel free to clone and make your own Prinvoice with your own app ID if you want
